### ISSUE TITLE
missing project task 'nugetInstall' in NuGetPlugin.groovy 

### ISSUE THREAD

**Issue by samalm321** [Ullink/gradle-nuget-plugin#39]
Hi,
I was trying to use nugetinstall but noticed that the task is missing on the NuGetPlugin.groovy.
As a workaround it's possible to invoke the NuGet.exe directly with a task with type:Exec through the method commandLine.

Sorry I can't contribute with a patch right now due to legal reasons.

**Comment by gluck** [comment]
The task type [does exist](https://github.com/Ullink/gradle-nuget-plugin/blob/master/src/main/groovy/com/ullink/NuGetInstall.groovy) but no default one is set when you apply nuget plugin.

You can use it though (e.g. it's [used in pdbindex plugin](https://github.com/Ullink/gradle-pdbindex-plugin/blob/master/src/main/groovy/com/ullink/SourceLinkExtension.groovy#L17)), syntax should be similar, e.g.:

        project.task(type: com.ullink.NuGetInstall, "fooBarInstall") {
            packageId = 'fooBar'
            outputDirectory = someDir
            includeVersionInPath = false
            version = '1.0.0'
        }

**Comment by samalm321** [comment]
Hi, thanks for that one :+1: Didn't know it could be done like this!
