### ISSUE TITLE
Posibility to specify nuget download url

### ISSUE THREAD

**Issue by vitia** [Ullink/gradle-nuget-plugin#43]
I'd like posibility to override nuget download web url (for offline builds) which currently is hardcoded in BaseNuGet exec:
def nugetUrl = "https://dist.nuget.org/win-x86-commandline/v${project.extensions.nuget.version}/nuget.exe"
It would be cool to be able to provide own url like this:
nuget {
    nugetUrl ="http://cache.local/nuget/3.3.0/nuget.exe"
}

**Comment by gluck** [comment]
Would be nice indeed, feeling like contributing it ?

**Comment by admsteck** [comment]
I've just started looking at gradle and would be happy to contribute a fix for this as well as allowing you to use 'latest' as the nuget version.  The only problem is that I am not sure how to test my changes locally before submitting the pull request.

**Comment by timotei** [comment]
@admsteck You can either create some tests in Specs we have so far, or, make a test project where you use the plugin and configure it like you want (In order to use the modified version you either install it locally, or do a `buildSrc` symbolic link - see more info https://docs.gradle.org/current/userguide/custom_plugins.html)

**Comment by admsteck** [comment]
Thanks @timotei. I went with the `buildSrc` option and confirmed that it uses the `nugetUrl` provided.

**Comment by vitaliusvs** [comment]
Appears that urls are case sensitive - this one opens fine:
https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe

However plugin builds lowercase url which fails:
https://dist.nuget.org/win-x86-commandline/v3.4.4/nuget.exe

<Error>
<script/>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:c6e5ef4b-0001-00d5-2cc8-d284b0000000 Time:2016-06-30T12:08:39.0913813Z
</Message>
</Error>

**Comment by gluck** [comment]
Seems the lowercase url works for <3.4.4 versions (tested with 3.4.3, both lowercase and cased urls work).
nUgEt is such a troll :trollface:

**Comment by gluck** [comment]
actually no, needs to be lowercase for <3.4.4 and cased for >=3.4.4
:trollface:

**Comment by gluck** [comment]
see #48

**Comment by imanushin** [comment]
@vitia, @gluck, change was done in this PR: https://github.com/Ullink/gradle-nuget-plugin/pull/62
