### ISSUE TITLE
Where are the releases?

### ISSUE THREAD

**Issue by redrezo** [Ullink/gradle-nuget-plugin#53]
The newest release tag is 2.15, wheras the newest version on maven central is 2.12.
Where are the newer releases?
The README states just add mavenCentral()

**Comment by timotei** [comment]
We're using bintray for the distribution: https://bintray.com/ullink/gradle-plugins/com.ullink.gradle:gradle-nuget-plugin and it contains the latest released version.

**Comment by redrezo** [comment]
Could you update the README to contain something like
```
repositories { 
  maven { 
    url "http://dl.bintray.com/ullink/gradle-plugins" 
  } 
}
```
