### ISSUE TITLE
Getting nugetRestore to do anything.

### ISSUE THREAD

**Issue by coactivechris** [Ullink/gradle-nuget-plugin#54]
Hey there.  

All I want is to have the nugetRestore to restore all the requisite packages for my solution file.

When I run

`gradle nugetRestore`

The command runs, and says 'up-to-date' when run.  But no nuget packages get restored.
I am running the command from the gradle root folder.  Sitting in my root folder is the sln file ,and in a subfolder are my projects.  If I run `nuget restore MySolution.sln` everthing works hunky dory.  All packages are restored.
My gradle configuration for nugetRestore looks like this
```
nugetRestore {
    solutionFile = 'Coactive.API.sln'
    packagesDirectory = 'packages'
}
```

A little help would be most appreciated on what I'm doing wrong.

**Comment by gluck** [comment]
Maybe run gradle with info log level to see what command it's calling (if any) ? (`gradle -i`)
Feel free to look at [ILRepack build log](https://ci.appveyor.com/project/gluck/il-repack) to see the expected output and compare to yours
```
:nugetRestore (Thread[main,5,main]) started.
:nugetRestore
Executing task ':nugetRestore' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Restoring NuGet packages 
Starting process 'command 'C:\Users\appveyor\.gradle\caches\nuget\3.5.0\NuGet.exe''. Working directory: C:\projects\il-repack Command: C:\Users\appveyor\.gradle\caches\nuget\3.5.0\NuGet.exe restore -NonInteractive -Verbosity normal
```

**Comment by coactivechris** [comment]
@gluck ,

Well-called, my friend.  It looks like the version of the gradle nuget package was an older one.  Once I upgraded to 2.12, it's now working like a champion.

Great stuff.  Thanks so much.
