### ISSUE TITLE
Update to Gradle 4.x

### ISSUE THREAD

**Issue by zosrothko** [Ullink/gradle-nuget-plugin#61]
Hi

Gradle 4.6 is the latest version of Gradle. Could you update your plugin to the Gradle 4.x API?
Thanks

**Comment by timotei** [comment]
@zosrothko Feel free to submit a PR :)

**Comment by imanushin** [comment]
@timotei, @zosrothko, done as part of these changes: https://github.com/Ullink/gradle-nuget-plugin/pull/62
