### ISSUE TITLE
Allow ad-hoc location to NuGet Executable

### ISSUE THREAD

**Issue by tomasjin** [Ullink/gradle-nuget-plugin#64]
Can the BaseNuGet.groovy be updated so that if user specifies relative/absolute path to NuGet via an executable Exec property, the default search mechanism should be bypassed?

nugetRestore {
    executable "nuget\\nuget-4.6.2.exe"
}

**Comment by timotei** [comment]
@tomasjin There is a PR opened that does what you want: https://github.com/Ullink/gradle-nuget-plugin/pull/62

**Comment by imanushin** [comment]
@tomasjin , it is in review now. Could you please also check is it api useful for you?

Please see ```nugetExePath``` option here: https://github.com/imanushin/gradle-nuget-plugin/blob/3d9b2d0fd042e1d3484c9b18e001d0dc4dfff1c7/README.md

**Comment by tomasjin** [comment]
The API looks much better now as most CI/CD servers are behind firewall. Many thanks for the new API.
