### ISSUE TITLE
Project configuration fails without nugetSources section in build.gradle

### ISSUE THREAD

**Issue by mmduyzend** [Ullink/gradle-nuget-plugin#66]
Currently (version 2.16), without a nugetSources section defined in build.gradle, project configuration fails with "Operation not specified for NuGetSources task."

Projects that do not require a functional nugetSources task should not need to define this section for project configuration to succeed: Any error due to a missing or malformed nugetSources section should only occur on an attempt to invoke the nugetSources task, not during project configuration.

**Comment by citizenmatt** [comment]
I'd be happy to send a PR for this. Not sure what the correct fix is though - simply move the validation checks from `project.afterEvaluate` to `exec`?

**Comment by gluck** [comment]
That or remove default `nugetSources` task creation from `NuGetPlugin` ?
Not sure it makes sense to have this task by default, sounds a bit of a special use case.

**Comment by gluck** [comment]
@darsen WDYT ?
