### ISSUE TITLE
does this plugin work with mono?

### ISSUE THREAD

**Issue by Vad1mo** [Ullink/gradle-nuget-plugin#9]
any chance you you could add an parameter to the plugin so it would work also with mono?

**Comment by gluck** [comment]
Hi,

I don't use mono, but it should be fairly simple to add.
Any chance you could try it out ? I think adding "mono" in the command lines will work, provided that nuget exe is compatible with mono (which I'd expect).

https://github.com/Ullink/gradle-nuget-plugin/blob/master/src/main/groovy/com/ullink/BaseNuGet.groovy#L41

Let me know.

**Comment by Vad1mo** [comment]
how can add mono as prefix?
with mono you use nuget in this way `mono /absolute/dir/nuget.exe params` currently its is hardcoded nuget to be the first parameter.

 `def commandLineArgs = [nugetExe]`

**Comment by gluck** [comment]
yes you need to change the plugin code and test it.
I could do the change but I can't test it, would've been great if you could.

Thanks

**Comment by gluck** [comment]
Mono support added by @jonathanmorley in PR #13 , feel free to test !
